# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e00149befd19a27cb438f8b9dcec0e85556655aa59dc9944b1591170366378e1ae1d92762376e266c357e6d2f5788d520cc4d6d1054f57bf38b35a1bc0aa17

test:
  secret_key_base: 811fe4dabbe769e52de88bff28838de3f5d0d5d27f5671ec49f5f74ee58fe07c3da43c2df9ebe6f13d20dd7b30de96de1b6efa86590dbc75293ca80ff3df9159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
